/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

import javax.swing.table.DefaultTableModel;
import CustomTable.TableActionCellEditor;
import CustomTable.TableActionCellRenderer;
import CustomTable.TableActionEvent;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JWindow;
import oopClasses.Employee;
import oopClasses.HR;

/**
 *
 * @author keith
 */
public class JframeEmpManagement extends javax.swing.JFrame {

    /**
     * Creates new form JframeEmpManagement
     */
    private DefaultTableModel employeeTbl;
    private Employee loggedEmployee;
    private HR hrEmployee;
    public static JWindow window;
    public JframeEmpManagement(Employee loggedEmployee) {
        window = new JWindow();
        this.loggedEmployee = loggedEmployee;
        initComponents();
        employeeTbl = (DefaultTableModel) jTableEmployeeList.getModel();
        setExtendedState(MAXIMIZED_BOTH);
        initHrUser(loggedEmployee);
        initTable();
        loadEmployeeTable();            
    }
    
    private void showOverlay () {
        window.setSize(this.getSize());
        window.setVisible(true);
        window.setLocationRelativeTo(this);
        window.setBackground(new Color(0, 0, 0, 200));
    }
    
    private void loadEmployeeTable () {
        if (hrEmployee != null) {
            List <Employee> employees = hrEmployee.loadEmployees();
            for (Employee employee: employees) {
                employeeTbl.addRow(new Object[] {
                    employee.getID(),
                    employee.getFirstName(),
                    employee.getLastName()});
            }
        }
    }
    
    // removes all contents of jtable
    private void clearTable () {
        employeeTbl.setRowCount(0);
    }
    
    // creates an HR object if employee is instance of HR class
    private void initHrUser (Employee loggedEmployee) {
        if (loggedEmployee instanceof HR) {
            // pass the info of the current employee to the hr object
            this.hrEmployee = new HR(loggedEmployee);
        }
    }
    
    // initializes jtable action events
    private void initTable () {
        TableActionEvent event = new TableActionEvent() {
            int chosenEmployeeID;
            @Override
            public void onEdit(int row) {
                chosenEmployeeID = Integer.parseInt(jTableEmployeeList.getValueAt(row, 0).toString());
                dispose();
                new JframeEmployeeForm(loggedEmployee, chosenEmployeeID).setVisible(true);
            }
            @Override
            public void onDelete(int row) {
                chosenEmployeeID = Integer.parseInt(jTableEmployeeList.getValueAt(row, 0).toString());
                String firstName = jTableEmployeeList.getValueAt(row, 1).toString();
                String lastName = jTableEmployeeList.getValueAt(row, 2).toString();
                int choice = JOptionPane.showConfirmDialog(JframeEmpManagement.this, "This operation will permanently delete " + firstName + " " + lastName + "\n Do you wish to proceed?", "Confirm deletion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (choice == JOptionPane.YES_OPTION) {
                    boolean deleted = hrEmployee.deleteEmployeeByID(chosenEmployeeID);
                    if (deleted) {
                        JOptionPane.showMessageDialog(JframeEmpManagement.this, "Employee record has been deleted", "Deleted", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(JframeEmpManagement.this, "Failed to delete record ", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    clearTable();
                    loadEmployeeTable();
                }               
            }
            @Override
            public void onView(int row) {
                chosenEmployeeID = Integer.parseInt(jTableEmployeeList.getValueAt(row, 0).toString());
                showOverlay();
                new JframeProfile(loggedEmployee, chosenEmployeeID).setVisible(true);
            }
        };
         jTableEmployeeList.getColumnModel().getColumn(3).setCellRenderer(new TableActionCellRenderer());
         jTableEmployeeList.getColumnModel().getColumn(3).setCellEditor(new TableActionCellEditor(event));
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelBg = new javax.swing.JPanel();
        jButtonDashboard = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelEmployeeList = new javax.swing.JLabel();
        jButtonAddNewEmployee = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmployeeList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBg.setBackground(new java.awt.Color(86, 98, 106));
        jPanelBg.setLayout(new java.awt.GridBagLayout());

        jButtonDashboard.setBackground(new java.awt.Color(0, 183, 229));
        jButtonDashboard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDashboard.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDashboard.setText("Back to Dashboard");
        jButtonDashboard.setPreferredSize(new java.awt.Dimension(146, 35));
        jButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDashboardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanelBg.add(jButtonDashboard, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(86, 98, 106));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(586, 50));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabelEmployeeList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmployeeList.setForeground(new java.awt.Color(0, 183, 229));
        jLabelEmployeeList.setText("EMPLOYEE LIST");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jLabelEmployeeList, gridBagConstraints);

        jButtonAddNewEmployee.setBackground(new java.awt.Color(21, 36, 46));
        jButtonAddNewEmployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAddNewEmployee.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddNewEmployee.setText("Add New Employee");
        jButtonAddNewEmployee.setPreferredSize(new java.awt.Dimension(147, 35));
        jButtonAddNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewEmployeeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel2.add(jButtonAddNewEmployee, gridBagConstraints);

        jTextFieldSearch.setText("Search by ID..");
        jTextFieldSearch.setPreferredSize(new java.awt.Dimension(147, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel2.add(jTextFieldSearch, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jTableEmployeeList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "First Name", "Last Name", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmployeeList.setRowHeight(30);
        jTableEmployeeList.setSelectionBackground(new java.awt.Color(0, 183, 229));
        jTableEmployeeList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableEmployeeList);
        if (jTableEmployeeList.getColumnModel().getColumnCount() > 0) {
            jTableEmployeeList.getColumnModel().getColumn(3).setMinWidth(130);
            jTableEmployeeList.getColumnModel().getColumn(3).setMaxWidth(130);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel3.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(38, 38, 38, 38);
        jPanelBg.add(jPanel1, gridBagConstraints);

        getContentPane().add(jPanelBg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
    private void jButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDashboardActionPerformed
       this.dispose();
       new JframeDashboard(loggedEmployee.getID()).setVisible(true);
    }//GEN-LAST:event_jButtonDashboardActionPerformed

    private void jButtonAddNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewEmployeeActionPerformed
        dispose();
        new JframeEmployeeForm(loggedEmployee).setVisible(true);         
    }//GEN-LAST:event_jButtonAddNewEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddNewEmployee;
    private javax.swing.JButton jButtonDashboard;
    private javax.swing.JLabel jLabelEmployeeList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmployeeList;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
