/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

import Core.DatabaseConnection;
import Core.UserAuthentication;
import java.sql.Connection;

/**
 *
 * @author keith
 */
public class JframeLogin extends javax.swing.JFrame {

    /**
     * Creates new form JframeLogin
     */
    private UserAuthentication userAuth;
    private Connection connection;
    public JframeLogin() {
        this.connection = DatabaseConnection.Connect();
        this.userAuth = new UserAuthentication(connection);
        initComponents();       
        this.setExtendedState(MAXIMIZED_BOTH);
        jLabelInvalid.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelBg = new javax.swing.JPanel();
        jLabelSignIn = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelInvalid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBg.setBackground(new java.awt.Color(86, 98, 106));
        jPanelBg.setLayout(new java.awt.GridBagLayout());

        jLabelSignIn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelSignIn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSignIn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tagged (1).png"))); // NOI18N
        jLabelSignIn.setText("MotorPH");
        jLabelSignIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelSignIn.setIconTextGap(15);
        jLabelSignIn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        jPanelBg.add(jLabelSignIn, gridBagConstraints);

        jTextFieldUsername.setPreferredSize(new java.awt.Dimension(300, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 15, 4, 15);
        jPanelBg.add(jTextFieldUsername, gridBagConstraints);

        jPasswordField.setPreferredSize(new java.awt.Dimension(300, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 15, 4, 15);
        jPanelBg.add(jPasswordField, gridBagConstraints);

        jButtonLogin.setBackground(new java.awt.Color(0, 183, 229));
        jButtonLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Login");
        jButtonLogin.setPreferredSize(new java.awt.Dimension(300, 35));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(9, 15, 9, 15);
        jPanelBg.add(jButtonLogin, gridBagConstraints);

        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanelBg.add(jLabelUsername, gridBagConstraints);

        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanelBg.add(jLabelPassword, gridBagConstraints);

        jLabelInvalid.setForeground(new java.awt.Color(255, 102, 102));
        jLabelInvalid.setText("Incorrect username or password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        jPanelBg.add(jLabelInvalid, gridBagConstraints);

        getContentPane().add(jPanelBg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
       String username = jTextFieldUsername.getText();
       String password = new String (jPasswordField.getPassword());
       
        int employeeID = userAuth.getAuthenticatedID(username, password);
        
        if (employeeID != -1) {
            this.dispose();
            new JframeDashboard(employeeID).setVisible(true);
        } else {
            jLabelInvalid.setVisible(true);
        }
       
    }//GEN-LAST:event_jButtonLoginActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JframeLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelInvalid;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSignIn;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanelBg;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
