/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

import Domains.AttendanceRecord;
import Domains.YearPeriod;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import oopClasses.AttendanceDatabase;
import oopClasses.DatabaseConnection;
import oopClasses.Employee;
import oopClasses.HoursCalculator;

/**
 *
 * @author keith
 */
public class JframeAttendance extends javax.swing.JFrame {

    /**
     * Creates new form JframeAttendance
     */
    private Employee loggedEmployee;
    private AttendanceDatabase attendanceDB;
    private DefaultTableModel attendanceTbl;
    private boolean dateYearChoosersEnabled;
    public JframeAttendance(Employee loggedEmployee) {
        this.dateYearChoosersEnabled = false;
        this.attendanceDB = new AttendanceDatabase(DatabaseConnection.Connect());
        this.loggedEmployee = loggedEmployee;
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.attendanceTbl = (DefaultTableModel) jTableAttendance.getModel();       
        this.dateYearChoosersEnabled = true;
        jLabelErrorMessage.setVisible(false);
    }
    
    
    private void clearTable () {
        attendanceTbl.setRowCount(0);
    }
    
    private YearPeriod getChosenPeriod () {
        int year = jYearChooser.getYear();
        int month = jMonthChooser.getMonth() + 1;
        return new YearPeriod(year, month);
    }
    
    private void loadAttendanceTable() {
        jLabelErrorMessage.setVisible(false);
        YearPeriod chosenPeriod = getChosenPeriod();
        List <AttendanceRecord> records = loggedEmployee.viewPersonalAttendance(loggedEmployee.getID(), chosenPeriod);
        if (records.isEmpty()) jLabelErrorMessage.setVisible(true);
        
        for (AttendanceRecord record: records) {
            LocalDate date = record.getDate();
            LocalTime timeIn = record.getTimeIn();
            LocalTime timeOut = record.getTimeOut();
            double workHours = HoursCalculator.calculateDailyHours(timeIn, timeOut);
            attendanceTbl.addRow(new Object [] { date, timeIn, timeOut, workHours});
        }
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jButtonBackToDashboard = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelSelectMonth = new javax.swing.JLabel();
        jMonthChooser = new com.toedter.calendar.JMonthChooser();
        jLabelSelectYear = new javax.swing.JLabel();
        jYearChooser = new com.toedter.calendar.JYearChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabelErrorMessage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAttendance = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(86, 98, 106));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jButtonBackToDashboard.setBackground(new java.awt.Color(0, 183, 229));
        jButtonBackToDashboard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonBackToDashboard.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBackToDashboard.setText("Back To Dashboard");
        jButtonBackToDashboard.setPreferredSize(new java.awt.Dimension(75, 35));
        jButtonBackToDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToDashboardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(jButtonBackToDashboard, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(86, 98, 106));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelSelectMonth.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSelectMonth.setText("Select Month");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 2, 0);
        jPanel1.add(jLabelSelectMonth, gridBagConstraints);

        jMonthChooser.setPreferredSize(new java.awt.Dimension(125, 30));
        jMonthChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jMonthChooserPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jMonthChooser, gridBagConstraints);

        jLabelSelectYear.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSelectYear.setText("Select Year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 2, 0);
        jPanel1.add(jLabelSelectYear, gridBagConstraints);

        jYearChooser.setPreferredSize(new java.awt.Dimension(68, 30));
        jYearChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jYearChooserPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel1.add(jYearChooser, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 183, 229));
        jLabel3.setText("MY ATTENDANCE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 9, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabelErrorMessage.setForeground(new java.awt.Color(255, 102, 102));
        jLabelErrorMessage.setText("No records found in this period");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        jPanel1.add(jLabelErrorMessage, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jTableAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time In", "Time Out", "Hours Worked"
            }
        ));
        jTableAttendance.setSelectionBackground(new java.awt.Color(0, 183, 229));
        jScrollPane1.setViewportView(jTableAttendance);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(38, 38, 38, 38);
        jPanel4.add(jPanel2, gridBagConstraints);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMonthChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jMonthChooserPropertyChange
        if (dateYearChoosersEnabled) {
            clearTable();
            loadAttendanceTable();
        }              
    }//GEN-LAST:event_jMonthChooserPropertyChange

    private void jButtonBackToDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToDashboardActionPerformed
        this.dispose();
        new JframeDashboard(loggedEmployee.getID()).setVisible(true);
    }//GEN-LAST:event_jButtonBackToDashboardActionPerformed

    private void jYearChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jYearChooserPropertyChange
        if (dateYearChoosersEnabled) {
            clearTable();
            loadAttendanceTable();
        }       
    }//GEN-LAST:event_jYearChooserPropertyChange

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackToDashboard;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelErrorMessage;
    private javax.swing.JLabel jLabelSelectMonth;
    private javax.swing.JLabel jLabelSelectYear;
    private com.toedter.calendar.JMonthChooser jMonthChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAttendance;
    private com.toedter.calendar.JYearChooser jYearChooser;
    // End of variables declaration//GEN-END:variables
}
