/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

import Domains.Payslip;
import Domains.YearPeriod;
import Model.Employee;
import Util.PdfProcessor;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author keith
 */
public class JframePayslip extends javax.swing.JFrame {

    /**
     * Creates new form JframePayslip
     */
    private Employee loggedEmployee;
    public JframePayslip(Employee loggedEmployee) {
        this.loggedEmployee = loggedEmployee;
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        jPanel3.setVisible(false);
        jLabelVerifyError.setVisible(false);
    }
    

    private YearPeriod getChosenPeriod () {
        int year = jYearChooser.getYear();
        int month = jMonthChooser.getMonth() + 1;
        return new YearPeriod(year, month);
    }
    
    private Payslip getPayslipDetails (YearPeriod period) {
        return loggedEmployee.viewPersonalSalary(period);
    }
    
    private void displayPayslipDetails () {
        jLabelVerifyError.setVisible(false);
        YearPeriod period = getChosenPeriod();
        Payslip payslip = getPayslipDetails(period);
        
        if (payslip.getWorkHours() == 0) {
            jLabelVerifyError.setVisible(true);
            return;
        }
        
        jPanel3.setVisible(true);
        jLabelHourlyRateAmount.setText(amountToString(loggedEmployee.getHourlyRate()));
        jLabelHoursWorked.setText(amountToString(payslip.getWorkHours()));
        jLabelBasicSalaryAmount.setText(amountToString(payslip.getBasicSalary()));
        jLabelRiceSubsidyAmount.setText(amountToString(payslip.getRiceSubsidy()));
        jLabelPhoneAllowanceAmount.setText(amountToString(payslip.getPhoneAllowance()));
        jLabelClothingAllowanceAmount.setText(amountToString(payslip.getClothingAllowance()));
        jLabelGrossPayAmount.setText(amountToString(payslip.getGrossPay()));
        jLabelSssAmount.setText(amountToString(payslip.getSssDeduction()));
        jLabelPhilhealthAmount.setText(amountToString(payslip.getPhilhealthDeduction()));
        jLabelPagibigAmount.setText(amountToString(payslip.getPagibigDeduction()));
        jLabelWithholdingTaxAmount.setText(amountToString(payslip.getTaxDeduction()));
        jLabelTotalDeductionsAmount.setText(amountToString(payslip.getTotalDeductions()));
        jLabelTakeHomePayAmount.setText(amountToString(payslip.getNetPay()));      
        
        enableControls(false);
    }
    
    private void enableControls (boolean status) {
        jMonthChooser.setEnabled(status);
        jYearChooser.setEnabled(status);
        jButtonGenerate.setEnabled(status);
    }
        
    
    private String amountToString (double amount) {
        return String.format("%.2f", amount);
    }
    
    private void redirectToDirectory(File file) {
        try {
            if (Desktop.isDesktopSupported()) {         
            Desktop desktop = Desktop.getDesktop();
            File parentDirectory = file.getParentFile();
            desktop.open(parentDirectory);
        }
        } catch (IOException e) {
            e.printStackTrace();
        }
        
    }
    
    private void showGeneratePayslipResult (File filePath) {
        JOptionPane.showMessageDialog(this, filePath != null? "Pdf successfully created at: " + filePath.getAbsolutePath() : "There was a problem generating the report", filePath != null ? "Success": "Error", filePath != null ? JOptionPane.INFORMATION_MESSAGE: JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jButtonBackToDashboard = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelSelectMonth = new javax.swing.JLabel();
        jMonthChooser = new com.toedter.calendar.JMonthChooser();
        jLabelSelectYear = new javax.swing.JLabel();
        jYearChooser = new com.toedter.calendar.JYearChooser();
        jButtonGenerate = new javax.swing.JButton();
        jLabelVerifyError = new javax.swing.JLabel();
        jLabelHeader = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelHourlyRateAmount = new javax.swing.JLabel();
        jLabelHoursWorked = new javax.swing.JLabel();
        jLabelBasicSalaryAmount = new javax.swing.JLabel();
        jLabelRiceSubsidyAmount = new javax.swing.JLabel();
        jLabelPhoneAllowanceAmount = new javax.swing.JLabel();
        jLabelClothingAllowanceAmount = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelGrossPayAmount = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabelTakeHomePayAmount = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabelSssAmount = new javax.swing.JLabel();
        jLabelPhilhealthAmount = new javax.swing.JLabel();
        jLabelPagibigAmount = new javax.swing.JLabel();
        jLabelWithholdingTaxAmount = new javax.swing.JLabel();
        jLabelTotalDeductionsAmount = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();
        jButtonSavePdf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(86, 98, 106));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButtonBackToDashboard.setBackground(new java.awt.Color(100, 110, 120));
        jButtonBackToDashboard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonBackToDashboard.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBackToDashboard.setText("Back To Dashboard");
        jButtonBackToDashboard.setFocusable(false);
        jButtonBackToDashboard.setPreferredSize(new java.awt.Dimension(75, 35));
        jButtonBackToDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToDashboardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jButtonBackToDashboard, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(86, 98, 106));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabelSelectMonth.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSelectMonth.setText("Select Month");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        jPanel2.add(jLabelSelectMonth, gridBagConstraints);

        jMonthChooser.setPreferredSize(new java.awt.Dimension(125, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 11, 0);
        jPanel2.add(jMonthChooser, gridBagConstraints);

        jLabelSelectYear.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSelectYear.setText("Select Year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        jPanel2.add(jLabelSelectYear, gridBagConstraints);

        jYearChooser.setPreferredSize(new java.awt.Dimension(64, 35));
        jYearChooser.setYear(2022);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        jPanel2.add(jYearChooser, gridBagConstraints);

        jButtonGenerate.setBackground(new java.awt.Color(0, 183, 229));
        jButtonGenerate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonGenerate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGenerate.setText("Generate");
        jButtonGenerate.setPreferredSize(new java.awt.Dimension(125, 35));
        jButtonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(19, 0, 0, 0);
        jPanel2.add(jButtonGenerate, gridBagConstraints);

        jLabelVerifyError.setForeground(new java.awt.Color(255, 102, 102));
        jLabelVerifyError.setText("No work hours found");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jLabelVerifyError, gridBagConstraints);

        jLabelHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelHeader.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHeader.setText("e-Payslip");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel2.add(jLabelHeader, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(86, 98, 106));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText(" EARNINGS");
        jPanel4.add(jLabel29, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jPanel4, gridBagConstraints);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hourly Rate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabel5, gridBagConstraints);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hours Worked");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabel6, gridBagConstraints);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Basic Salary");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabel7, gridBagConstraints);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Rice Subsidy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabel8, gridBagConstraints);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone Allowance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabel9, gridBagConstraints);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Clothing Allowance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabel10, gridBagConstraints);

        jLabelHourlyRateAmount.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHourlyRateAmount.setText("jLabel11");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabelHourlyRateAmount, gridBagConstraints);

        jLabelHoursWorked.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHoursWorked.setText("jLabel12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabelHoursWorked, gridBagConstraints);

        jLabelBasicSalaryAmount.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBasicSalaryAmount.setText("jLabel13");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabelBasicSalaryAmount, gridBagConstraints);

        jLabelRiceSubsidyAmount.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRiceSubsidyAmount.setText("jLabel14");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabelRiceSubsidyAmount, gridBagConstraints);

        jLabelPhoneAllowanceAmount.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPhoneAllowanceAmount.setText("jLabel15");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabelPhoneAllowanceAmount, gridBagConstraints);

        jLabelClothingAllowanceAmount.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClothingAllowanceAmount.setText("jLabel16");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabelClothingAllowanceAmount, gridBagConstraints);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gross Pay");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabel17, gridBagConstraints);

        jLabelGrossPayAmount.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGrossPayAmount.setText("jLabel18");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabelGrossPayAmount, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText(" DEDUCTIONS");
        jPanel5.add(jLabel30, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jPanel5, gridBagConstraints);

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("SSS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabel19, gridBagConstraints);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Philhealth");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabel20, gridBagConstraints);

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Pag-ibig");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabel21, gridBagConstraints);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Withholding Tax");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabel22, gridBagConstraints);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText(" TAKE HOME PAY:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        jPanel6.add(jLabel31, gridBagConstraints);

        jLabelTakeHomePayAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTakeHomePayAmount.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        jPanel6.add(jLabelTakeHomePayAmount, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jPanel6, gridBagConstraints);

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Total Deductions");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabel23, gridBagConstraints);

        jLabelSssAmount.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSssAmount.setText("jLabel24");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabelSssAmount, gridBagConstraints);

        jLabelPhilhealthAmount.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPhilhealthAmount.setText("jLabel25");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabelPhilhealthAmount, gridBagConstraints);

        jLabelPagibigAmount.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPagibigAmount.setText("jLabel26");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabelPagibigAmount, gridBagConstraints);

        jLabelWithholdingTaxAmount.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWithholdingTaxAmount.setText("jLabel27");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabelWithholdingTaxAmount, gridBagConstraints);

        jLabelTotalDeductionsAmount.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalDeductionsAmount.setText("jLabel28");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 2, 40);
        jPanel3.add(jLabelTotalDeductionsAmount, gridBagConstraints);

        jPanel7.setBackground(new java.awt.Color(86, 98, 106));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jButtonClose.setBackground(new java.awt.Color(153, 0, 0));
        jButtonClose.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel7.add(jButtonClose, gridBagConstraints);

        jButtonSavePdf.setBackground(new java.awt.Color(100, 110, 120));
        jButtonSavePdf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSavePdf.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSavePdf.setText("Save PDF");
        jButtonSavePdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSavePdfActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel7.add(jButtonSavePdf, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(jPanel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel3, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateActionPerformed
        displayPayslipDetails();
    }//GEN-LAST:event_jButtonGenerateActionPerformed

    private void jButtonBackToDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToDashboardActionPerformed
        this.dispose();
        new JframeDashboard(loggedEmployee.getID()).setVisible(true);
    }//GEN-LAST:event_jButtonBackToDashboardActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        jPanel3.setVisible(false);
        enableControls(true);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonSavePdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSavePdfActionPerformed
        YearPeriod period = getChosenPeriod();
        File filePath = PdfProcessor.createPayslipPdf(getPayslipDetails(period));
        showGeneratePayslipResult(filePath);
        redirectToDirectory(filePath);
    }//GEN-LAST:event_jButtonSavePdfActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackToDashboard;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonGenerate;
    private javax.swing.JButton jButtonSavePdf;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBasicSalaryAmount;
    private javax.swing.JLabel jLabelClothingAllowanceAmount;
    private javax.swing.JLabel jLabelGrossPayAmount;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelHourlyRateAmount;
    private javax.swing.JLabel jLabelHoursWorked;
    private javax.swing.JLabel jLabelPagibigAmount;
    private javax.swing.JLabel jLabelPhilhealthAmount;
    private javax.swing.JLabel jLabelPhoneAllowanceAmount;
    private javax.swing.JLabel jLabelRiceSubsidyAmount;
    private javax.swing.JLabel jLabelSelectMonth;
    private javax.swing.JLabel jLabelSelectYear;
    private javax.swing.JLabel jLabelSssAmount;
    private javax.swing.JLabel jLabelTakeHomePayAmount;
    private javax.swing.JLabel jLabelTotalDeductionsAmount;
    private javax.swing.JLabel jLabelVerifyError;
    private javax.swing.JLabel jLabelWithholdingTaxAmount;
    private com.toedter.calendar.JMonthChooser jMonthChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private com.toedter.calendar.JYearChooser jYearChooser;
    // End of variables declaration//GEN-END:variables
}
