/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorphpayrollv2;

import java.awt.Image;
import java.time.LocalDate;
import java.time.Month;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author keith
 */
public class JframeDashboard extends javax.swing.JFrame {

    /**
     * Creates new form JframeDashboard
     */
    public JframeDashboard() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        addPic();
        loadInfo();
        
 
    }
    
    private void addPic () {
        ImageIcon logoIcon2 = new ImageIcon(getClass().getResource("/images/www (1).png"));
        Image img2= logoIcon2.getImage().getScaledInstance(jLabel8.getWidth(), jLabel8.getHeight(), Image.SCALE_SMOOTH);
        logoIcon2 = new ImageIcon(img2);
        jLabel8.setIcon(logoIcon2);
        
        ImageIcon logoIcon = new ImageIcon(getClass().getResource("/images/www (1).png"));
        Image img = logoIcon.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);
        logoIcon = new ImageIcon(img);
        jLabel4.setIcon(logoIcon);             
        
        ImageIcon logoIcon3 = new ImageIcon(getClass().getResource("/images/theone.jpg"));
        Image img3 = logoIcon3.getImage().getScaledInstance(jLabel17.getWidth(), jLabel17.getHeight(), Image.SCALE_SMOOTH);
        logoIcon3 = new ImageIcon(img3);
        jLabel17.setIcon(logoIcon3); 
    }
    
    private void loadInfo () {
        jLabelEmployeeID.setText("<html>Employee ID: <b>10001</b></html>");
        jLabelFullName.setText("Name: Andrea Mae Villanueva");
        jLabelBirthday.setText("Birthday: 2003-23-05");
        jLabelPhoneNumber.setText("Phone: 966-860-270");
        jLabelSssNumber.setText("SSS: 44-4506057-3");
        jLabelPhilhealthNumber.setText("Philhealth: 820126853951");
        jLabelTin.setText("TIN: 442-605-657-000");
        jLabelPagibig.setText("Pagibig: 691295330870");
        jLabelStatus.setText("Status: Regular");
        jLabelPosition.setText("Position: Chief Executive Officer");
        jLabelRole.setText("Role: Employee");
        jLabelBasicSalary.setText("Basic Salary: 90000.00");
        jLabelRiceSubsidy.setText("Rice Subsidy: 1500.00");
        jLabelPhoneAllowance.setText("Phone Allowance: 2000.00");
        jLabelClothingAllowance.setText("Clothing Allowance: 1000.00");
        jLabelHourlyRate.setText("Hourly Rate: 535.70");      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelLeft = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButtonAttendance = new javax.swing.JButton();
        jButtonPayroll = new javax.swing.JButton();
        jButtonLeave = new javax.swing.JButton();
        jButtonEmployeeManagement = new javax.swing.JButton();
        jButtonAttendanceManagement = new javax.swing.JButton();
        jButtonLeaveManagement = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelRight = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelTop = new javax.swing.JPanel();
        jPanelMid = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabelEmployeeID = new javax.swing.JLabel();
        jLabelSssNumber = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jLabelRiceSubsidy = new javax.swing.JLabel();
        jLabelFullName = new javax.swing.JLabel();
        jLabelPhilhealthNumber = new javax.swing.JLabel();
        jLabelPosition = new javax.swing.JLabel();
        jLabelPhoneAllowance = new javax.swing.JLabel();
        jLabelBirthday = new javax.swing.JLabel();
        jLabelTin = new javax.swing.JLabel();
        jLabelRole = new javax.swing.JLabel();
        jLabelClothingAllowance = new javax.swing.JLabel();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jLabelPagibig = new javax.swing.JLabel();
        jLabelBasicSalary = new javax.swing.JLabel();
        jLabelHourlyRate = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel15 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanelLeft.setBackground(new java.awt.Color(21, 36, 46));
        jPanelLeft.setPreferredSize(new java.awt.Dimension(200, 444));
        jPanelLeft.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(21, 36, 46));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 183, 229));
        jLabel1.setText(" NAVIGATIONS");
        jLabel1.setPreferredSize(new java.awt.Dimension(89, 35));
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelLeft.add(jPanel2, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(21, 36, 46));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 40));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 183, 229));
        jLabel3.setText(" NAVIGATIONS");
        jLabel3.setPreferredSize(new java.awt.Dimension(89, 35));
        jPanel1.add(jLabel3, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelLeft.add(jPanel1, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(21, 36, 46));
        jPanel3.setLayout(new java.awt.GridLayout(4, 2));

        jButton12.setBackground(new java.awt.Color(21, 36, 46));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("jButton12");
        jPanel3.add(jButton12);

        jButton13.setBackground(new java.awt.Color(0, 183, 229));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("jButton13");
        jPanel3.add(jButton13);

        jButton16.setBackground(new java.awt.Color(0, 183, 229));
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("jButton16");
        jPanel3.add(jButton16);

        jButton14.setBackground(new java.awt.Color(21, 36, 46));
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("jButton14");
        jPanel3.add(jButton14);

        jButton15.setBackground(new java.awt.Color(0, 183, 229));
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("jButton15");
        jPanel3.add(jButton15);

        jButton18.setBackground(new java.awt.Color(21, 36, 46));
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("jButton18");
        jPanel3.add(jButton18);

        jButton17.setBackground(new java.awt.Color(21, 36, 46));
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("jButton17");
        jPanel3.add(jButton17);

        jButton19.setBackground(new java.awt.Color(0, 183, 229));
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("jButton19");
        jPanel3.add(jButton19);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelLeft.add(jPanel3, gridBagConstraints);

        jButtonAttendance.setText("Attendance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelLeft.add(jButtonAttendance, gridBagConstraints);

        jButtonPayroll.setText("Payroll");
        jButtonPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayrollActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelLeft.add(jButtonPayroll, gridBagConstraints);

        jButtonLeave.setText("Leave");
        jButtonLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelLeft.add(jButtonLeave, gridBagConstraints);

        jButtonEmployeeManagement.setText("Employee Management");
        jButtonEmployeeManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmployeeManagementActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelLeft.add(jButtonEmployeeManagement, gridBagConstraints);

        jButtonAttendanceManagement.setText("Attendance Management");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelLeft.add(jButtonAttendanceManagement, gridBagConstraints);

        jButtonLeaveManagement.setText("Leave Management");
        jButtonLeaveManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaveManagementActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelLeft.add(jButtonLeaveManagement, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(21, 36, 46));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 183, 229));
        jLabel2.setText(" GRAPH");
        jLabel2.setPreferredSize(new java.awt.Dimension(89, 35));
        jPanel4.add(jLabel2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelLeft.add(jPanel4, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel4.setMaximumSize(new java.awt.Dimension(100, 70));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 70));
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel5.add(jLabel4, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelLeft.add(jPanel5, gridBagConstraints);

        getContentPane().add(jPanelLeft, java.awt.BorderLayout.LINE_START);

        jPanelRight.setBackground(new java.awt.Color(21, 36, 46));
        jPanelRight.setPreferredSize(new java.awt.Dimension(200, 444));
        jPanelRight.setLayout(new java.awt.GridBagLayout());

        jPanel10.setBackground(new java.awt.Color(21, 36, 46));
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 183, 229));
        jLabel5.setText(" NOTIFICATIONS");
        jPanel10.add(jLabel5, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        jPanelRight.add(jPanel10, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 150));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 150));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setMaximumSize(new java.awt.Dimension(45, 90));
        jList1.setMinimumSize(new java.awt.Dimension(45, 50));
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        jPanelRight.add(jScrollPane1, gridBagConstraints);

        jPanel6.setBackground(new java.awt.Color(21, 36, 46));
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 183, 229));
        jLabel6.setText(" TIME LOGGING");
        jPanel6.add(jLabel6, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        jPanelRight.add(jPanel6, gridBagConstraints);

        jPanel7.setBackground(new java.awt.Color(21, 36, 46));
        jPanel7.setLayout(new java.awt.GridLayout(3, 2));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pen (2).png"))); // NOI18N
        jPanel7.add(jButton1);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 183, 229));
        jLabel9.setText(" Clock In");
        jPanel7.add(jLabel9);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eye.png"))); // NOI18N
        jPanel7.add(jButton2);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 183, 229));
        jLabel10.setText(" Clock Out");
        jPanel7.add(jLabel10);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove.png"))); // NOI18N
        jPanel7.add(jButton3);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 183, 229));
        jLabel11.setText(" Logout");
        jPanel7.add(jLabel11);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanelRight.add(jPanel7, gridBagConstraints);

        jPanel8.setBackground(new java.awt.Color(21, 36, 46));
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 183, 229));
        jLabel7.setText(" GRAPHS");
        jPanel8.add(jLabel7, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanelRight.add(jPanel8, gridBagConstraints);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel8.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel8.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel9.add(jLabel8, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelRight.add(jPanel9, gridBagConstraints);

        getContentPane().add(jPanelRight, java.awt.BorderLayout.LINE_END);

        jPanelTop.setBackground(new java.awt.Color(204, 204, 204));
        jPanelTop.setPreferredSize(new java.awt.Dimension(653, 20));

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 869, Short.MAX_VALUE)
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        jPanelMid.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMid.setLayout(new java.awt.GridBagLayout());

        jPanel11.setBackground(new java.awt.Color(0, 183, 229));
        jPanel11.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" EMPLOYEE INFORMATION");
        jPanel11.add(jLabel12, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        jPanelMid.add(jPanel11, gridBagConstraints);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.GridLayout(4, 4));

        jLabelEmployeeID.setText("Employee ID: 10001");
        jPanel12.add(jLabelEmployeeID);

        jLabelSssNumber.setText("SSS: 44-4506057-3");
        jPanel12.add(jLabelSssNumber);

        jLabelStatus.setText("Status:");
        jPanel12.add(jLabelStatus);

        jLabelRiceSubsidy.setText("RiceSubsidy:");
        jPanel12.add(jLabelRiceSubsidy);

        jLabelFullName.setText("Name: Manuel Garcia");
        jPanel12.add(jLabelFullName);

        jLabelPhilhealthNumber.setText("Philhealth: ");
        jPanel12.add(jLabelPhilhealthNumber);

        jLabelPosition.setText("Position:");
        jPanel12.add(jLabelPosition);

        jLabelPhoneAllowance.setText("PhoneAllowance:");
        jPanel12.add(jLabelPhoneAllowance);

        jLabelBirthday.setText("Birthday: 1983-10-11");
        jPanel12.add(jLabelBirthday);

        jLabelTin.setText("TIN:");
        jPanel12.add(jLabelTin);

        jLabelRole.setText("Role:");
        jPanel12.add(jLabelRole);

        jLabelClothingAllowance.setText("Clothing allowance:");
        jPanel12.add(jLabelClothingAllowance);

        jLabelPhoneNumber.setText("Phone: 966-860-270");
        jPanel12.add(jLabelPhoneNumber);

        jLabelPagibig.setText("Pagibig:");
        jPanel12.add(jLabelPagibig);

        jLabelBasicSalary.setText("BasicSalary:");
        jPanel12.add(jLabelBasicSalary);

        jLabelHourlyRate.setText("Hourly Rate:");
        jPanel12.add(jLabelHourlyRate);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        jPanelMid.add(jPanel12, gridBagConstraints);

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" INFORMATION");
        jPanel13.add(jLabel13, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        jPanelMid.add(jPanel13, gridBagConstraints);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(469, 110));
        jPanel14.setLayout(new java.awt.GridBagLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel17.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.9;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel14.add(jPanel17, gridBagConstraints);

        jPanel18.setBackground(new java.awt.Color(0, 51, 102));
        jPanel18.setLayout(new java.awt.BorderLayout());
        jPanel18.add(jCalendar1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel14.add(jPanel18, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelMid.add(jPanel14, gridBagConstraints);

        jPanel15.setBackground(new java.awt.Color(51, 51, 51));
        jPanel15.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" INFORMATION AGAIN");
        jPanel15.add(jLabel14, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        jPanelMid.add(jPanel15, gridBagConstraints);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setPreferredSize(new java.awt.Dimension(469, 130));
        jPanel16.setLayout(new java.awt.GridLayout(1, 2));

        jLabel16.setText("jLabel16");
        jPanel16.add(jLabel16);

        jLabel17.setText("jLabel17");
        jPanel16.add(jLabel17);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        jPanelMid.add(jPanel16, gridBagConstraints);

        getContentPane().add(jPanelMid, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEmployeeManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmployeeManagementActionPerformed
        this.dispose();
        new JframeEmpManagement().setVisible(true);
    }//GEN-LAST:event_jButtonEmployeeManagementActionPerformed

    private void jButtonLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaveActionPerformed
        this.dispose();
        new JframeLeave().setVisible(true);
    }//GEN-LAST:event_jButtonLeaveActionPerformed

    private void jButtonLeaveManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaveManagementActionPerformed
        this.dispose();
        new JframeLeaveManagement().setVisible(true);
    }//GEN-LAST:event_jButtonLeaveManagementActionPerformed

    private void jButtonPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayrollActionPerformed
        this.dispose();
        new JframePayslip().setVisible(true);
    }//GEN-LAST:event_jButtonPayrollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAttendance;
    private javax.swing.JButton jButtonAttendanceManagement;
    private javax.swing.JButton jButtonEmployeeManagement;
    private javax.swing.JButton jButtonLeave;
    private javax.swing.JButton jButtonLeaveManagement;
    private javax.swing.JButton jButtonPayroll;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBasicSalary;
    private javax.swing.JLabel jLabelBirthday;
    private javax.swing.JLabel jLabelClothingAllowance;
    private javax.swing.JLabel jLabelEmployeeID;
    private javax.swing.JLabel jLabelFullName;
    private javax.swing.JLabel jLabelHourlyRate;
    private javax.swing.JLabel jLabelPagibig;
    private javax.swing.JLabel jLabelPhilhealthNumber;
    private javax.swing.JLabel jLabelPhoneAllowance;
    private javax.swing.JLabel jLabelPhoneNumber;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JLabel jLabelRiceSubsidy;
    private javax.swing.JLabel jLabelRole;
    private javax.swing.JLabel jLabelSssNumber;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTin;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelMid;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
