/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CustomTable;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author admin
 */
public class PanelActionV3 extends javax.swing.JPanel {

    /**
     * Creates new form PanelActionV3
     */
    public PanelActionV3() {
        initComponents();
    }
    
    public void initEvent (TableActionEventV3 event, int row) {
        jButtonAdustCredits.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                event.adjustCredits(row);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButtonAdustCredits = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jButtonAdustCredits.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAdustCredits.setText("Adjust Credits");
        jButtonAdustCredits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAdustCreditsMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jButtonAdustCredits, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdustCreditsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdustCreditsMouseEntered
        // TODO add your handling code here:
        jButtonAdustCredits.setBackground(new Color(0,183,229));
    }//GEN-LAST:event_jButtonAdustCreditsMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdustCredits;
    // End of variables declaration//GEN-END:variables
}
