/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ui;

import Model.CredentialsDAO;
import Model.TwoFactorAuthService;
import java.awt.Frame;
import java.sql.SQLException;

/**
 *
 * @author admin
 */
public class JDialogVerify2FA extends javax.swing.JDialog {

    /**
     * Creates new form JDialogVerify2FA
     */
    private final int employeeID;
    private Frame parent;
    public JDialogVerify2FA(java.awt.Frame parent, boolean modal, int employeeID) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.employeeID = employeeID;
        jLabelCodeError.setVisible(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jButtonVerify = new javax.swing.JButton();
        jLabelCodeError = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 330));

        jPanel1.setBackground(new java.awt.Color(86, 98, 106));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOTP Verification");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(40, 35, 5, 35);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter 6-digit code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jTextFieldCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCode.setPreferredSize(new java.awt.Dimension(71, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 35);
        jPanel1.add(jTextFieldCode, gridBagConstraints);

        jButtonVerify.setBackground(new java.awt.Color(0, 183, 229));
        jButtonVerify.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonVerify.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerify.setText("Verify");
        jButtonVerify.setPreferredSize(new java.awt.Dimension(75, 35));
        jButtonVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerifyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 35, 40, 35);
        jPanel1.add(jButtonVerify, gridBagConstraints);

        jLabelCodeError.setForeground(new java.awt.Color(255, 102, 102));
        jLabelCodeError.setText("This is required");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel1.add(jLabelCodeError, gridBagConstraints);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter the code from your authenticator app");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerifyActionPerformed
        // TODO add your handling code here:
        jLabelCodeError.setVisible(false);
        try {
            int code = Integer.parseInt(jTextFieldCode.getText());
            
            try {
                CredentialsDAO dao = new CredentialsDAO();
                String totpSecret = dao.getTotpSecretByEmployeeID(employeeID);
            
                boolean isAuthenticated = TwoFactorAuthService.verifyCode(totpSecret, code);
                if (!isAuthenticated) {
                    jLabelCodeError.setText("Incorrect 6 digit code");
                    jLabelCodeError.setVisible(true);
                    return;
                }
                
                JframeDashboard dashboard = new JframeDashboard(employeeID);
                dashboard.setVisible(true);
                this.dispose();
                parent.dispose();
                
            } catch (SQLException e) {
                e.printStackTrace();
            }
  
        } catch (NumberFormatException e) {
            jLabelCodeError.setText("Code should be a 6-digit integer");
            jLabelCodeError.setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonVerifyActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVerify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCodeError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCode;
    // End of variables declaration//GEN-END:variables
}
