/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui;

import CustomTable.TableActionCellEditorV3;
import CustomTable.TableActionCellRendererV3;
import CustomTable.TableActionEventV3;
import Model.LeaveBalance;
import Model.Employee;
import Dao.LeaveCreditsDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

/**
 *
 * @author admin
 */
public class JframeLeaveCredits extends javax.swing.JFrame {

    private Employee loggedEmployee;
    /**
     * Creates new form JframeLeaveCredits
     * @param loggedEmployee
     */
    public JframeLeaveCredits(Employee loggedEmployee) {
        this.loggedEmployee = loggedEmployee;
        initComponents();
        initTableEvents();
        setExtendedState(MAXIMIZED_BOTH);
        loadTable();
    }
    
    private void setUpActionColumn (TableActionEventV3 event) {
        jTableLeaveCredits.getColumnModel().getColumn(4).setCellRenderer(new TableActionCellRendererV3());
        jTableLeaveCredits.getColumnModel().getColumn(4).setCellEditor(new TableActionCellEditorV3(event));
    }
    
    private void initTableEvents () {
        TableActionEventV3 events = createTableActionEvents();
        setUpActionColumn(events);
    }
    
    private void clearTableSelection() {
        jTableLeaveCredits.clearSelection();
        if (jTableLeaveCredits.getCellEditor() != null) {
            jTableLeaveCredits.getCellEditor().stopCellEditing();
        }
    }
    
    private TableActionEventV3 createTableActionEvents () {
        return new TableActionEventV3() {
            @Override
            public void adjustCredits(int row) {
                int employeeID = getIdFromRow(row);
                new JDialogLeaveCredits(JframeLeaveCredits.this, true, employeeID).setVisible(true);
                clearTableSelection();
                loadTable();
            }
        };
    }
    
    private int getIdFromRow(int row) {
        return (int) jTableLeaveCredits.getValueAt(row, 0);
    }
    
    private Object [] createTableRowData(LeaveBalance balance) {
        return new Object [] {
            balance.getEmployeeID(),
            balance.getVacationLeaveCredits(),
            balance.getMedicalLeaveCredits(),
            balance.getPersonalLeaveCredits()
        };
    }
    
    private void populateTable(List<LeaveBalance> balances) {
        DefaultTableModel model = (DefaultTableModel) jTableLeaveCredits.getModel();
        model.setRowCount(0);
        for (LeaveBalance balance: balances) {
            model.addRow(createTableRowData(balance));
        }
        
    }
    
    private void loadTable() {
        try {
            LeaveCreditsDAO dao = new LeaveCreditsDAO();
            List<LeaveBalance> balances = dao.getAllEmployeeLeaveCredits();
            populateTable(balances);
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLeaveCredits = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(86, 98, 106));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(86, 98, 106));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton1.setText(" Back To Dashboard");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(75, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.01;
        jPanel1.add(jButton1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LEAVE CREDITS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(38, 38, 0, 38);
        jPanel1.add(jLabel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jTableLeaveCredits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Vacation Credits", "Medical Credits", "Personal Credits", "Action"
            }
        ));
        jTableLeaveCredits.setRowHeight(30);
        jTableLeaveCredits.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTableLeaveCredits.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTableLeaveCredits);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(38, 38, 38, 38);
        jPanel1.add(jPanel2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new JframeDashboard(loggedEmployee.getID()).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLeaveCredits;
    // End of variables declaration//GEN-END:variables
}
